// Searchable sticker set — each sticker carries keywords so typing "tired",
// "proud", "coffee" finds it the way a messenger sticker search would.
export const STICKERS = [
  { char: "😀", tags: "happy smile good day joy" },
  { char: "🥰", tags: "love loved soft warm" },
  { char: "😌", tags: "calm relieved peace ok" },
  { char: "🤩", tags: "excited amazing win great" },
  { char: "😅", tags: "barely made it chaos survived" },
  { char: "😭", tags: "cry sad hard rough" },
  { char: "😤", tags: "frustrated angry mad done" },
  { char: "😵‍💫", tags: "overwhelmed dizzy too much overstimulated" },
  { char: "🥱", tags: "tired sleepy exhausted yawn" },
  { char: "😐", tags: "meh flat neutral fine" },
  { char: "🫠", tags: "melting burnt out done overwhelmed" },
  { char: "🧠", tags: "brain adhd thoughts spicy" },
  { char: "🌀", tags: "spiral scattered chaos brain fog" },
  { char: "✨", tags: "sparkle magic good proud" },
  { char: "🎉", tags: "celebrate win party done" },
  { char: "🏆", tags: "win trophy proud achievement" },
  { char: "✅", tags: "done finished complete check" },
  { char: "📌", tags: "task pinned note important" },
  { char: "🔥", tags: "fire streak momentum crushing it" },
  { char: "💪", tags: "strong showed up effort proud" },
  { char: "🐌", tags: "slow snail slow day gentle" },
  { char: "🛏️", tags: "rest bed nap sleep recover" },
  { char: "☕", tags: "coffee caffeine morning" },
  { char: "🍵", tags: "tea calm cozy" },
  { char: "🍕", tags: "pizza food ate treat" },
  { char: "🥗", tags: "food healthy ate lunch" },
  { char: "💧", tags: "water hydrated drink" },
  { char: "💊", tags: "meds medication took them" },
  { char: "🚶", tags: "walk moved outside steps" },
  { char: "🏃", tags: "run exercise moved workout" },
  { char: "🧘", tags: "calm breathe meditate reset" },
  { char: "🧺", tags: "laundry chores home" },
  { char: "🧹", tags: "clean tidy chores home" },
  { char: "🍽️", tags: "dishes chores kitchen" },
  { char: "🛒", tags: "groceries errand shopping" },
  { char: "🚗", tags: "drive errand car trip" },
  { char: "💻", tags: "work laptop focus computer" },
  { char: "📚", tags: "study read school learning" },
  { char: "📝", tags: "wrote notes journal plan" },
  { char: "📞", tags: "call phone talked" },
  { char: "💬", tags: "talked conversation vent" },
  { char: "🫶", tags: "love support grateful thanks" },
  { char: "🙏", tags: "grateful thanks please hope" },
  { char: "❤️", tags: "love heart happy" },
  { char: "💛", tags: "warm heart friend love" },
  { char: "🩵", tags: "calm heart blue soft" },
  { char: "🌱", tags: "growth progress small start new" },
  { char: "🌻", tags: "sunny hopeful flower bright" },
  { char: "🌈", tags: "hope rainbow better after" },
  { char: "☀️", tags: "sunny good weather bright" },
  { char: "🌧️", tags: "rain gloomy low mood" },
  { char: "⛈️", tags: "storm rough hard day" },
  { char: "🌙", tags: "night late evening sleep" },
  { char: "⭐", tags: "star good highlight win" },
  { char: "🎯", tags: "focus goal target hit it" },
  { char: "⏰", tags: "time late reminder clock" },
  { char: "🐢", tags: "slow turtle pace steady" },
  { char: "🐈", tags: "cat pet animal" },
  { char: "🐕", tags: "dog pet walk animal" },
  { char: "🎵", tags: "music song listened" },
  { char: "🎮", tags: "games play rest fun" },
  { char: "🎨", tags: "art creative made something" },
  { char: "🧩", tags: "puzzle figured out problem" },
  { char: "💡", tags: "idea thought realization" },
  { char: "🫥", tags: "invisible withdrawn low hiding" },
  { char: "🤝", tags: "help support together" },
  { char: "🚀", tags: "launch started momentum go" },
];

export function searchStickers(query) {
  const q = query.trim().toLowerCase();
  if (!q) return STICKERS;
  return STICKERS.filter((s) => s.tags.includes(q) || s.char === q);
}